name: CI

on: 
  workflow_dispatch:  # <--- Esta línea es la que activa el botón
  push:
    branches:
      - master
jobs:
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: 3.11

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json || true #FUERZO QUE TEMINE OK PARA QUE SIGA EL FLUJO. 

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json

 build_image_scan:
   name: Build Image and Run Image Scan
#   needs: sast_scan <-- Esta es la clave para que el job se ejecute después del análisis SAST 
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4
# Este paso ya no es necesario porque la última version de Ubuntu ya viene con Docker preinstalado
#  - name: Set up Docker
#    uses: docker-practice/actions-setup-docker@v1
#    # with:
#     # docker_version: '20.10.7'
   # 1. Necesio login primero
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.REPO_USER }}
       password: ${{ secrets.REPO_PWD }}

   # 2. Ahora sí puedes buildear y pushear
   - name: Build and push Image
     uses: docker/build-push-action@v5
     with:
       push: true
       tags: ${{ secrets.REPO_USER }}/pygoat:latest
      

   # - name: Docker Scout Scan
     # run: |
       # curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       # sh install-scout.sh
       # echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
       # docker scout quickview
       # docker scout cves

   - name: Docker Scout Scan
     uses: docker/scout-action@v1
     with:
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif
   - name: Upload SARIF results to GitHub Security
     uses: github/codeql-action/upload-sarif@v3
     if: always()
     with:
       sarif_file: scout-report.sarif